export const FILE_HEADER = '// @generated by flowprint -- DO NOT EDIT\n\n'

export function indent(text: string, level: number): string {
  const prefix = '  '.repeat(level)
  return text
    .split('\n')
    .map((line) => (line.trim() === '' ? '' : prefix + line))
    .join('\n')
}

export function emitImport(specifiers: string[], from: string): string {
  if (specifiers.length === 0) return ''
  return `import { ${specifiers.join(', ')} } from '${from}'`
}

export function emitTypeImport(specifiers: string[], from: string): string {
  if (specifiers.length === 0) return ''
  return `import type { ${specifiers.join(', ')} } from '${from}'`
}

export function camelCase(snakeCase: string): string {
  return snakeCase.replace(/[-_]([a-z])/g, (_, letter: string) => letter.toUpperCase())
}

export function pascalCase(snakeCase: string): string {
  const camel = camelCase(snakeCase)
  const first = camel[0]
  if (!first) return ''
  return first.toUpperCase() + camel.slice(1)
}
