import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { parse } from 'yaml'
import type { FlowprintDocument } from '@ruminaider/flowprint-schema'
import { generateCode } from '../../codegen/index.js'

const FIXTURE_PATH = resolve(
  import.meta.dirname,
  '../../../../..',
  'examples/consultation-flow-v2.flowprint.yaml',
)

function loadConsultationFlowV2(): FlowprintDocument {
  const content = readFileSync(FIXTURE_PATH, 'utf-8')
  return parse(content) as FlowprintDocument
}

describe('codegen integration', () => {
  it('generates all expected files from consultation-flow-v2', () => {
    const doc = loadConsultationFlowV2()
    const result = generateCode(doc, {
      outputDir: './generated',
      flowName: doc.name,
    })

    const paths = result.files.map((f) => f.path)
    expect(paths).toContain('workflow.ts')
    expect(paths).toContain('activities.ts')
    expect(paths).toContain('worker.ts')
    expect(paths).toContain('types.ts')
    expect(paths).toContain('activity-mocks.ts')
    expect(paths).toContain('test-fixtures.ts')
    expect(paths).toContain('signal-fixtures.ts')
  })

  it('all files have the generated header', () => {
    const doc = loadConsultationFlowV2()
    const result = generateCode(doc, {
      outputDir: './generated',
      flowName: doc.name,
    })

    for (const file of result.files) {
      expect(file.content).toMatch(/^\/\/ @generated by flowprint/)
    }
  })

  it('workflow file contains Temporal imports', () => {
    const doc = loadConsultationFlowV2()
    const result = generateCode(doc, {
      outputDir: './generated',
      flowName: doc.name,
    })

    const workflow = result.files.find((f) => f.path === 'workflow.ts')
    expect(workflow).toBeDefined()
    expect(workflow?.content).toContain("from '@temporalio/workflow'")
    expect(workflow?.content).toContain('proxyActivities')
    expect(workflow?.content).toContain('defineSignal')
    expect(workflow?.content).toContain('setHandler')
    expect(workflow?.content).toContain('condition')
    expect(workflow?.content).toContain('upsertSearchAttributes')
  })

  it('workflow file contains ConsultationInput type import', () => {
    const doc = loadConsultationFlowV2()
    const result = generateCode(doc, {
      outputDir: './generated',
      flowName: doc.name,
    })

    const workflow = result.files.find((f) => f.path === 'workflow.ts')
    expect(workflow?.content).toContain('ConsultationInput')
    expect(workflow?.content).toContain("from './types'")
  })

  it('activities file contains re-exports for action nodes', () => {
    const doc = loadConsultationFlowV2()
    const result = generateCode(doc, {
      outputDir: './generated',
      flowName: doc.name,
    })

    const activities = result.files.find((f) => f.path === 'activities.ts')
    expect(activities).toBeDefined()
    expect(activities?.content).toContain('initiateConsultation')
    expect(activities?.content).toContain('collectIntake')
    expect(activities?.content).toContain('escalateEmergency')
  })

  it('activities file contains compensation re-exports', () => {
    const doc = loadConsultationFlowV2()
    const result = generateCode(doc, {
      outputDir: './generated',
      flowName: doc.name,
    })

    const activities = result.files.find((f) => f.path === 'activities.ts')
    expect(activities?.content).toContain('escalateEmergencyCompensate')
    expect(activities?.content).toContain('assignSpecialistCompensate')
  })

  it('worker file uses configured task queue', () => {
    const doc = loadConsultationFlowV2()
    const result = generateCode(doc, {
      outputDir: './generated',
      flowName: doc.name,
    })

    const worker = result.files.find((f) => f.path === 'worker.ts')
    expect(worker?.content).toContain("taskQueue: 'consultation-tasks'")
  })

  it('types file re-exports ConsultationInput and ProviderAvailableSignal', () => {
    const doc = loadConsultationFlowV2()
    const result = generateCode(doc, {
      outputDir: './generated',
      flowName: doc.name,
    })

    const types = result.files.find((f) => f.path === 'types.ts')
    expect(types?.content).toContain('ConsultationInput')
    expect(types?.content).toContain('ProviderAvailableSignal')
  })

  it('signal fixtures file contains ProviderAvailableSignal fixture', () => {
    const doc = loadConsultationFlowV2()
    const result = generateCode(doc, {
      outputDir: './generated',
      flowName: doc.name,
    })

    const signalFixtures = result.files.find((f) => f.path === 'signal-fixtures.ts')
    expect(signalFixtures).toBeDefined()
    expect(signalFixtures?.content).toContain('ProviderAvailableSignal')
  })

  it('generated workflow code contains valid syntax markers', () => {
    const doc = loadConsultationFlowV2()
    const result = generateCode(doc, {
      outputDir: './generated',
      flowName: doc.name,
    })

    const workflow = result.files.find((f) => f.path === 'workflow.ts')
    expect(workflow).toBeDefined()
    const content = workflow?.content ?? ''

    // Check for basic syntax validity markers
    expect(content).toContain('export async function')
    expect(content).toContain('import {')
    expect(content).toContain("from '@temporalio/workflow'")

    // Balanced braces (rough check)
    const openBraces = (content.match(/\{/g) ?? []).length
    const closeBraces = (content.match(/\}/g) ?? []).length
    expect(openBraces).toBe(closeBraces)
  })

  it('workflow contains compensation try/catch block', () => {
    const doc = loadConsultationFlowV2()
    const result = generateCode(doc, {
      outputDir: './generated',
      flowName: doc.name,
    })

    const workflow = result.files.find((f) => f.path === 'workflow.ts')
    expect(workflow?.content).toContain('compensationStack')
    expect(workflow?.content).toContain('try {')
    expect(workflow?.content).toContain('catch (err)')
    expect(workflow?.content).toContain('compensationStack.reverse()')
  })

  it('workflow contains wait node signal handling', () => {
    const doc = loadConsultationFlowV2()
    const result = generateCode(doc, {
      outputDir: './generated',
      flowName: doc.name,
    })

    const workflow = result.files.find((f) => f.path === 'workflow.ts')
    expect(workflow?.content).toContain("'provider.available'")
    expect(workflow?.content).toContain('ProviderAvailableSignal')
    expect(workflow?.content).toContain('setHandler')
    expect(workflow?.content).toContain("'2h'")
  })

  it('returns correct flowName in result', () => {
    const doc = loadConsultationFlowV2()
    const result = generateCode(doc, {
      outputDir: './generated',
      flowName: doc.name,
    })
    expect(result.flowName).toBe('consultation-flow')
  })
})
