import { describe, it, expect } from 'vitest'
import type { FlowprintDocument } from '@ruminaider/flowprint-schema'
import { generateWorker } from '../../codegen/worker-generator.js'

function makeDoc(
  overrides: Partial<FlowprintDocument> & { nodes: FlowprintDocument['nodes'] },
): FlowprintDocument {
  return {
    schema: 'flowprint/2.0',
    name: 'test-flow',
    version: '1.0.0',
    lanes: {
      default: { label: 'Default', visibility: 'internal', order: 0 },
    },
    ...overrides,
  }
}

describe('generateWorker', () => {
  it('generates file header', () => {
    const doc = makeDoc({
      nodes: {
        done: {
          type: 'terminal',
          lane: 'default',
          label: 'Done',
          outcome: 'success',
        },
      },
    })
    const result = generateWorker(doc)
    expect(result.path).toBe('worker.ts')
    expect(result.content).toMatch(/^\/\/ @generated by flowprint/)
  })

  it('uses flow name as default task queue', () => {
    const doc = makeDoc({
      name: 'my-workflow',
      nodes: {
        done: {
          type: 'terminal',
          lane: 'default',
          label: 'Done',
          outcome: 'success',
        },
      },
    })
    const result = generateWorker(doc)
    expect(result.content).toContain("taskQueue: 'my-workflow'")
  })

  it('uses custom task queue from workflow config', () => {
    const doc = makeDoc({
      workflow: {
        task_queue: 'custom-queue',
      },
      nodes: {
        done: {
          type: 'terminal',
          lane: 'default',
          label: 'Done',
          outcome: 'success',
        },
      },
    })
    const result = generateWorker(doc)
    expect(result.content).toContain("taskQueue: 'custom-queue'")
  })

  it('includes environment variable usage for address', () => {
    const doc = makeDoc({
      nodes: {
        done: {
          type: 'terminal',
          lane: 'default',
          label: 'Done',
          outcome: 'success',
        },
      },
    })
    const result = generateWorker(doc)
    expect(result.content).toContain('process.env.TEMPORAL_ADDRESS')
    expect(result.content).toContain("'localhost:7233'")
  })

  it('includes environment variable usage for namespace', () => {
    const doc = makeDoc({
      nodes: {
        done: {
          type: 'terminal',
          lane: 'default',
          label: 'Done',
          outcome: 'success',
        },
      },
    })
    const result = generateWorker(doc)
    expect(result.content).toContain('process.env.TEMPORAL_NAMESPACE')
    expect(result.content).toContain("'default'")
  })

  it('imports NativeConnection and Worker from @temporalio/worker', () => {
    const doc = makeDoc({
      nodes: {
        done: {
          type: 'terminal',
          lane: 'default',
          label: 'Done',
          outcome: 'success',
        },
      },
    })
    const result = generateWorker(doc)
    expect(result.content).toContain(
      "import { NativeConnection, Worker } from '@temporalio/worker'",
    )
    expect(result.content).toContain("import * as activities from './activities'")
  })
})
