/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Node = ActionNode | SwitchNode | ParallelNode | WaitNode | ErrorNode | TerminalNode

/**
 * A service blueprint definition mapping business processes to code entry points
 */
export interface FlowprintServiceBlueprint {
  /**
   * Schema version identifier (e.g. flowprint/1.0)
   */
  schema: string
  /**
   * Machine-readable blueprint name
   */
  name: string
  /**
   * Semantic version of this blueprint
   */
  version: string
  /**
   * Human-readable description of the blueprint
   */
  description?: string
  /**
   * Custom key-value metadata (e.g. owner, domain, tags)
   */
  metadata?: {
    [k: string]: string
  }
  /**
   * Swimlane definitions keyed by lane ID
   */
  lanes: {
    [k: string]: Lane
  }
  /**
   * Node definitions keyed by node ID
   */
  nodes: {
    [k: string]: Node
  }
}
export interface Lane {
  /**
   * Human-readable lane display name
   */
  label: string
  /**
   * Whether this lane is customer-facing (external) or internal
   */
  visibility: 'external' | 'internal'
  /**
   * Display order (0 = topmost lane)
   */
  order: number
}
export interface ActionNode {
  type: 'action'
  lane: string
  label: string
  description?: string
  metadata?: {
    [k: string]: string
  }
  entry_points?: EntryPoint[]
  next?: string
  error?: ErrorHandler
}
export interface EntryPoint {
  /**
   * Relative file path from repo root
   */
  file: string
  /**
   * Function/method name in the file
   */
  symbol: string
}
export interface ErrorHandler {
  retry?: {
    /**
     * Maximum number of retry attempts
     */
    limit: number
    /**
     * Backoff strategy for retries
     */
    backoff?: 'linear' | 'exponential'
  }
  /**
   * Node ID to handle the error
   */
  catch?: string
}
export interface SwitchNode {
  type: 'switch'
  lane: string
  label: string
  description?: string
  metadata?: {
    [k: string]: string
  }
  entry_points?: EntryPoint[]
  /**
   * @minItems 1
   */
  cases: [
    {
      when: string
      next: string
    },
    ...{
      when: string
      next: string
    }[],
  ]
  default?: string
}
export interface ParallelNode {
  type: 'parallel'
  lane: string
  label: string
  description?: string
  metadata?: {
    [k: string]: string
  }
  entry_points?: EntryPoint[]
  /**
   * @minItems 1
   */
  branches: [string, ...string[]]
  join: string
  join_strategy?: 'all_reached' | 'await_all'
}
export interface WaitNode {
  type: 'wait'
  lane: string
  label: string
  description?: string
  metadata?: {
    [k: string]: string
  }
  entry_points?: EntryPoint[]
  /**
   * Event name to wait for
   */
  event: string
  /**
   * Duration string (e.g. 7d, 24h, 30m)
   */
  timeout?: string
  next?: string
  /**
   * Node to route to when timeout expires
   */
  timeout_next?: string
}
export interface ErrorNode {
  type: 'error'
  lane: string
  label: string
  description?: string
  metadata?: {
    [k: string]: string
  }
  entry_points?: EntryPoint[]
  next?: string
}
export interface TerminalNode {
  type: 'terminal'
  lane: string
  label: string
  metadata?: {
    [k: string]: string
  }
  /**
   * Whether this terminal represents a successful or failed outcome
   */
  outcome: 'success' | 'failure'
}
