/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Node = ActionNode | SwitchNode | ParallelNode | WaitNode | ErrorNode | TerminalNode | TriggerNode;
export type TriggerNode = {
  [k: string]: unknown;
} & {
  type: "trigger";
  lane: string;
  label: string;
  description?: string;
  /**
   * Markdown notes for documentation and design rationale
   */
  notes?: string;
  metadata?: {
    [k: string]: string;
  };
  position?: Position;
  trigger_type: "schedule" | "webhook" | "event" | "manual";
  /**
   * Node ID that this trigger initiates
   */
  next: string;
  schedule?: {
    cron?: string;
    timezone?: string;
  };
  webhook?: {
    method?: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
    path?: string;
    headers?: {
      [k: string]: string;
    };
  };
  event?: {
    source?: string;
    type?: string;
    filter?: string;
  };
  manual?: {
    form_fields?: {
      name?: string;
      type?: "string" | "number" | "boolean";
      required?: boolean;
    }[];
  };
};

/**
 * A service blueprint definition mapping business processes to code entry points
 */
export interface FlowprintServiceBlueprint {
  /**
   * Schema version identifier (e.g. flowprint/1.0)
   */
  schema: string;
  /**
   * Machine-readable blueprint name
   */
  name: string;
  /**
   * Semantic version of this blueprint
   */
  version: string;
  /**
   * Human-readable description of the blueprint
   */
  description?: string;
  /**
   * Custom key-value metadata (e.g. owner, domain, tags)
   */
  metadata?: {
    [k: string]: string;
  };
  /**
   * External secrets this workflow needs at runtime (names and descriptions only, never values)
   */
  secrets?: {
    [k: string]: {
      /**
       * Human-readable description of what this secret is for
       */
      description: string;
    };
  };
  /**
   * Workflow-level execution configuration
   */
  workflow?: {
    /**
     * Temporal task queue name
     */
    task_queue?: string;
    /**
     * Overall workflow execution timeout (e.g. 1h, 30m)
     */
    execution_timeout?: string;
    /**
     * TypeScript type name for workflow input
     */
    input_type?: string;
    /**
     * Module path to import input type from (default: ./types)
     */
    input_type_import?: string;
  };
  /**
   * Swimlane definitions keyed by lane ID
   */
  lanes: {
    [k: string]: Lane;
  };
  /**
   * Node definitions keyed by node ID
   */
  nodes: {
    [k: string]: Node;
  };
}
export interface Lane {
  /**
   * Human-readable lane display name
   */
  label: string;
  /**
   * Whether this lane is customer-facing (external) or internal
   */
  visibility: "external" | "internal";
  /**
   * Display order (0 = topmost lane)
   */
  order: number;
  /**
   * Optional custom lane height in pixels (minimum 140)
   */
  height?: number;
}
export interface ActionNode {
  type: "action";
  lane: string;
  label: string;
  description?: string;
  /**
   * Markdown notes for documentation and design rationale
   */
  notes?: string;
  metadata?: {
    [k: string]: string;
  };
  entry_points?: EntryPoint[];
  rules?: RulesRef;
  position?: Position;
  /**
   * Named input mapping: parameter name to expression
   */
  inputs?: {
    [k: string]: string;
  };
  compensation?: EntryPoint1;
  temporal?: TemporalConfig;
  next?: string;
  error?: ErrorHandler;
}
export interface EntryPoint {
  /**
   * Relative file path from repo root
   */
  file: string;
  /**
   * Function/method name in the file
   */
  symbol: string;
}
export interface RulesRef {
  /**
   * Relative path to .rules.yaml file
   */
  file: string;
  /**
   * Evaluator plugin name (default: builtin)
   */
  evaluator?: string;
}
export interface Position {
  x: number;
  y: number;
}
/**
 * Compensation function for saga-style rollback
 */
export interface EntryPoint1 {
  /**
   * Relative file path from repo root
   */
  file: string;
  /**
   * Function/method name in the file
   */
  symbol: string;
}
/**
 * Per-activity Temporal configuration
 */
export interface TemporalConfig {
  /**
   * Maximum time an activity can take from start to completion
   */
  start_to_close_timeout?: string;
  /**
   * Maximum time from scheduling to completion including retries
   */
  schedule_to_close_timeout?: string;
  /**
   * Maximum time between heartbeats
   */
  heartbeat_timeout?: string;
  /**
   * Retry policy configuration
   */
  retry?: {
    /**
     * Maximum number of retry attempts
     */
    max_attempts?: number;
    /**
     * Retry backoff multiplier
     */
    backoff_coefficient?: number;
    /**
     * Initial retry interval
     */
    initial_interval?: string;
    /**
     * Maximum retry interval
     */
    max_interval?: string;
    /**
     * Error types that should not be retried
     */
    non_retryable_errors?: string[];
  };
}
export interface ErrorHandler {
  retry?: {
    /**
     * Maximum number of retry attempts
     */
    limit: number;
    /**
     * Backoff strategy for retries
     */
    backoff?: "linear" | "exponential";
  };
  /**
   * Node ID to handle the error
   */
  catch?: string;
}
export interface SwitchNode {
  type: "switch";
  lane: string;
  label: string;
  description?: string;
  /**
   * Markdown notes for documentation and design rationale
   */
  notes?: string;
  metadata?: {
    [k: string]: string;
  };
  entry_points?: EntryPoint[];
  rules?: RulesRef;
  position?: Position;
  cases?: {
    when: string;
    next: string;
  }[];
  default?: string;
}
export interface ParallelNode {
  type: "parallel";
  lane: string;
  label: string;
  description?: string;
  /**
   * Markdown notes for documentation and design rationale
   */
  notes?: string;
  metadata?: {
    [k: string]: string;
  };
  entry_points?: EntryPoint[];
  position?: Position;
  branches: string[];
  join: string;
  join_strategy?: "all" | "first";
}
export interface WaitNode {
  type: "wait";
  lane: string;
  label: string;
  description?: string;
  /**
   * Markdown notes for documentation and design rationale
   */
  notes?: string;
  metadata?: {
    [k: string]: string;
  };
  entry_points?: EntryPoint[];
  position?: Position;
  /**
   * Event name to wait for
   */
  event: string;
  /**
   * TypeScript type name for signal payload
   */
  event_type?: string;
  /**
   * Module path to import event type from (default: ./types)
   */
  event_type_import?: string;
  /**
   * Duration string (e.g. 7d, 24h, 30m)
   */
  timeout?: string;
  next?: string;
  /**
   * Node to route to when timeout expires
   */
  timeout_next?: string;
}
export interface ErrorNode {
  type: "error";
  lane: string;
  label: string;
  description?: string;
  /**
   * Markdown notes for documentation and design rationale
   */
  notes?: string;
  metadata?: {
    [k: string]: string;
  };
  entry_points?: EntryPoint[];
  position?: Position;
  next?: string;
}
export interface TerminalNode {
  type: "terminal";
  lane: string;
  label: string;
  /**
   * Markdown notes for documentation and design rationale
   */
  notes?: string;
  metadata?: {
    [k: string]: string;
  };
  position?: Position;
  /**
   * Whether this terminal represents a successful or failed outcome
   */
  outcome: "success" | "failure";
}
