import { describe, it, expect } from 'vitest'
import type { FlowprintDocument } from '@ruminaider/flowprint-schema'
import { generateActivities } from '../../codegen/activities-generator.js'

function makeDoc(
  overrides: Partial<FlowprintDocument> & { nodes: FlowprintDocument['nodes'] },
): FlowprintDocument {
  return {
    schema: 'flowprint/1.0',
    name: 'test-flow',
    version: '1.0.0',
    lanes: {
      default: { label: 'Default', visibility: 'internal', order: 0 },
    },
    ...overrides,
  }
}

describe('generateActivities', () => {
  it('generates file header', () => {
    const doc = makeDoc({
      nodes: {
        done: {
          type: 'terminal',
          lane: 'default',
          label: 'Done',
          outcome: 'success',
        },
      },
    })
    const result = generateActivities(doc)
    expect(result.path).toBe('activities.ts')
    expect(result.content).toMatch(/^\/\/ @generated by flowprint/)
  })

  it('generates simple re-export for action node', () => {
    const doc = makeDoc({
      nodes: {
        create_order: {
          type: 'action',
          lane: 'default',
          label: 'Create Order',
          entry_points: [{ file: 'src/orders.ts', symbol: 'createOrder' }],
          next: 'done',
        },
        done: {
          type: 'terminal',
          lane: 'default',
          label: 'Done',
          outcome: 'success',
        },
      },
    })
    const result = generateActivities(doc)
    expect(result.content).toContain("export { createOrder as createOrder } from 'src/orders.ts'")
  })

  it('generates wrapper function when inputs are defined', () => {
    const doc = makeDoc({
      nodes: {
        process_payment: {
          type: 'action',
          lane: 'default',
          label: 'Process Payment',
          entry_points: [{ file: 'src/pay.ts', symbol: 'processPayment' }],
          inputs: {
            amount: 'input.total',
            currency: 'input.currency',
          },
          next: 'done',
        },
        done: {
          type: 'terminal',
          lane: 'default',
          label: 'Done',
          outcome: 'success',
        },
      },
    })
    const result = generateActivities(doc)
    expect(result.content).toContain('import { processPayment as _processPayment }')
    expect(result.content).toContain('export async function processPayment')
    expect(result.content).toContain('amount: unknown; currency: unknown')
    expect(result.content).toContain('const { amount, currency } = args')
    expect(result.content).toContain('return _processPayment(amount, currency)')
  })

  it('generates compensation re-export', () => {
    const doc = makeDoc({
      nodes: {
        reserve_item: {
          type: 'action',
          lane: 'default',
          label: 'Reserve Item',
          entry_points: [{ file: 'src/inventory.ts', symbol: 'reserve' }],
          compensation: {
            file: 'src/inventory.ts',
            symbol: 'releaseReservation',
          },
          next: 'done',
        },
        done: {
          type: 'terminal',
          lane: 'default',
          label: 'Done',
          outcome: 'success',
        },
      },
    })
    const result = generateActivities(doc)
    expect(result.content).toContain("export { reserve as reserveItem } from 'src/inventory.ts'")
    expect(result.content).toContain(
      "export { releaseReservation as reserveItemCompensate } from 'src/inventory.ts'",
    )
  })

  it('generates exports for multiple action nodes', () => {
    const doc = makeDoc({
      nodes: {
        step_a: {
          type: 'action',
          lane: 'default',
          label: 'Step A',
          entry_points: [{ file: 'src/a.ts', symbol: 'doA' }],
          next: 'step_b',
        },
        step_b: {
          type: 'action',
          lane: 'default',
          label: 'Step B',
          entry_points: [{ file: 'src/b.ts', symbol: 'doB' }],
          next: 'done',
        },
        done: {
          type: 'terminal',
          lane: 'default',
          label: 'Done',
          outcome: 'success',
        },
      },
    })
    const result = generateActivities(doc)
    expect(result.content).toContain("export { doA as stepA } from 'src/a.ts'")
    expect(result.content).toContain("export { doB as stepB } from 'src/b.ts'")
  })

  it('skips nodes without entry points', () => {
    const doc = makeDoc({
      nodes: {
        no_entry: {
          type: 'action',
          lane: 'default',
          label: 'No Entry Points',
          next: 'done',
        },
        done: {
          type: 'terminal',
          lane: 'default',
          label: 'Done',
          outcome: 'success',
        },
      },
    })
    const result = generateActivities(doc)
    expect(result.content).not.toContain('noEntry')
  })

  it('skips non-action non-error nodes', () => {
    const doc = makeDoc({
      nodes: {
        wait_node: {
          type: 'wait',
          lane: 'default',
          label: 'Wait',
          event: 'some.event',
          next: 'done',
        },
        done: {
          type: 'terminal',
          lane: 'default',
          label: 'Done',
          outcome: 'success',
        },
      },
    })
    const result = generateActivities(doc)
    expect(result.content).not.toContain('waitNode')
  })

  it('generates export for error node with entry points', () => {
    const doc = makeDoc({
      nodes: {
        handle_error: {
          type: 'error',
          lane: 'default',
          label: 'Handle Error',
          entry_points: [{ file: 'src/errors.ts', symbol: 'handleError' }],
          next: 'done',
        },
        done: {
          type: 'terminal',
          lane: 'default',
          label: 'Done',
          outcome: 'success',
        },
      },
    })
    const result = generateActivities(doc)
    expect(result.content).toContain("export { handleError as handleError } from 'src/errors.ts'")
  })

  it('generates evaluator activity for action node with rules', () => {
    const doc = makeDoc({
      nodes: {
        calculate_discount: {
          type: 'action',
          lane: 'default',
          label: 'Calculate Discount',
          rules: { file: 'discount.rules.yaml' },
          next: 'done',
        },
        done: {
          type: 'terminal',
          lane: 'default',
          label: 'Done',
          outcome: 'success',
        },
      },
    })
    const result = generateActivities(doc)
    expect(result.content).toContain('// Calculate Discount (rules-driven)')
    expect(result.content).toContain('export async function evaluateCalculateDiscountRules')
    expect(result.content).toContain("loadRulesFile('discount.rules.yaml', process.cwd())")
    expect(result.content).toContain('evaluateRules(doc, { input, results: new Map() })')
    expect(result.content).toContain(
      "import { loadRulesFile, evaluateRules } from '@ruminaider/flowprint-engine'",
    )
  })

  it('generates evaluator activity for switch node with rules', () => {
    const doc = makeDoc({
      nodes: {
        route_order: {
          type: 'switch',
          lane: 'default',
          label: 'Route Order',
          rules: { file: 'routing.rules.yaml' },
          cases: [{ when: 'true', next: 'done' }],
        },
        done: {
          type: 'terminal',
          lane: 'default',
          label: 'Done',
          outcome: 'success',
        },
      },
    })
    const result = generateActivities(doc)
    expect(result.content).toContain('// Route Order (rules-driven)')
    expect(result.content).toContain('export async function evaluateRouteOrderRules')
    expect(result.content).toContain("loadRulesFile('routing.rules.yaml', process.cwd())")
    expect(result.content).toContain(
      "import { loadRulesFile, evaluateRules } from '@ruminaider/flowprint-engine'",
    )
  })
})
